title: GSAI学习资源
description: 中国人民大学高瓴人工智能学院学习资源汇总
theme: jekyll-theme-minimal # 或者您选择的其他主题

# 添加导航链接
header_pages:
  - README.md
  - start.md
  - 大一课程/人工智能与python/readme.md
  - 大一课程/程序设计/readme.md
  - GSAI-STUDY/5.注意事项.md

# 设置默认布局
defaults:
  - scope:
      path: ""
    values:
      layout: default

# 启用集合功能
collections:
  大一课程:
    output: true
  GSAI-STUDY:
    output: true